[build]
  publish = "."

[context.production]
  environment = { }

[context.deploy-preview]
  environment = { }

[context.branch-deploy]
  environment = { }

# Redirects for clean URLs
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
